# -*- coding: utf-8 -*-
"""ML_assign_2_q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ANF3R8pva8R0ApX_hsLymMI1KEG591xT
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
path = Path('/content/drive/My Drive/assignment_2/exp_train.csv')
path_test = Path('/content/drive/My Drive/assignment_2/exp_test.csv')

import pandas as pd
names =[
't', # Time (secs)
'q1', 'q2', 'q3', # Joint angle
'dq1', 'dq2', 'dq3', # Joint velocity
'I1', 'I2', 'I3', # Motor current (A)
'eps21', 'eps22', 'eps31', 'eps32', # Strain measurements
'ddq1', 'ddq2', 'ddq3' # Joint accelerations
]
df = pd.read_csv(path, header=None,sep=',',
names=names, index_col=0)
df.head(6)

y = df['I2'];y.shape

X = df[['q2', 'dq2', 'eps21', 'eps22', 'eps31', 'eps32', 'ddq2']];X.shape

from sklearn import metrics, linear_model
regr = linear_model.LinearRegression()

regr.fit(X, y)

names =[
't', # Time (secs)
'q1', 'q2', 'q3', # Joint angle
'dq1', 'dq2', 'dq3', # Joint velocity
'I1', 'I2', 'I3', # Motor current (A)
'eps21', 'eps22', 'eps31', 'eps32', # Strain measurements
'ddq1', 'ddq2', 'ddq3' # Joint accelerations
]
df_test = pd.read_csv(path_test, header=None,sep=',',
names=names, index_col=0)
df_test.head(6)

y_test = df_test['I2']
X_test = df_test[['q2', 'dq2', 'eps21', 'eps22', 'eps31', 'eps32', 'ddq2']]

y_pred = regr.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score
print('Coefficients: \n', regr.coef_)
print('\n')
print('Mean squared error for testing dataset: %.2f'% mean_squared_error(y_test, y_pred))
print('\n')
print('R-Squared value: %.2f'% r2_score(y_test, y_pred))